# GitHub Quarterly Report Configuration
# Configuration for generating quarterly reports from GitHub repositories

# GitHub Organization (optional - if all repos are under the same org)
github_org: "your-organization"

# List of repositories to analyze (without org prefix if github_org is set)
repositories:
  - "repo1"
  - "repo2" 
  - "repo3"
  # Add more repositories as needed

# Team member mapping (GitHub username -> Display name)
team_members:
  "github_username1": "John Doe"
  "github_username2": "Jane Smith"
  "octocat": "GitHub Mascot"
  # Add more team members as needed

# Report settings
report_settings:
  # Maximum results per API call (GitHub allows up to 100)
  max_results: 100
  
  # Include private repositories (requires appropriate token permissions)
  include_private: true
  
  # Activity types to track
  track_pull_requests: true
  track_commits: true
  track_issues: true
  track_code_reviews: false  # Future enhancement
  
  # Date range preferences
  timezone: "UTC"
  
  # Output preferences  
  max_contributors_in_overview: 15
  max_recent_items_per_contributor: 10
  
# GitHub API settings
api_settings:
  # Rate limiting (GitHub allows 5000 requests per hour for authenticated users)
  rate_limit_buffer: 100  # Reserve some requests for other operations
  
  # Request timeout in seconds
  timeout: 30
  
  # Retry settings
  max_retries: 3
  retry_delay: 1  # seconds

# Repository filters (optional)
repository_filters:
  # Exclude archived repositories
  exclude_archived: true
  
  # Exclude forked repositories
  exclude_forks: true
  
  # Only include repositories with activity in the date range
  only_active_repos: true

# Contributor filters (optional)
contributor_filters:
  # Exclude bot accounts
  exclude_bots: true
  
  # Bot patterns to exclude (case-insensitive)
  bot_patterns:
    - "bot"
    - "dependabot"
    - "renovate"
    - "github-actions"
  
  # Minimum activity threshold (exclude contributors with less activity)
  min_contributions: 1

# Report customization
report_customization:
  # Include repository descriptions in output
  include_repo_descriptions: false
  
  # Include code change statistics (lines added/removed)
  include_code_stats: true
  
  # Include time-based analysis
  include_monthly_breakdown: true
  
  # Custom report title
  report_title: "GitHub Quarterly Contributor Report"
  
  # Custom footer text
  footer_text: "Generated by GitHub Quarterly Report Tool"
